//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarbiTtiTFA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zarbittiDBEntities : DbContext
    {
        public zarbittiDBEntities()
            : base("name=zarbittiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrito> carrito { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<detallesCompra> detallesCompra { get; set; }
        public virtual DbSet<estadoCarrito> estadoCarrito { get; set; }
        public virtual DbSet<imagenSlide> imagenSlide { get; set; }
        public virtual DbSet<miembro> miembro { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rolMiembro> rolMiembro { get; set; }
        public virtual DbSet<producto> producto { get; set; }
    }
}
