//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarbiTtiTFA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.carrito = new HashSet<carrito>();
        }
    
        public int IDProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fechaDeCreacion { get; set; }
        public Nullable<System.DateTime> fechaDeModificacion { get; set; }
        public string descripcion { get; set; }
        public string ProductImage { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrito> carrito { get; set; }
        public virtual categoria categoria { get; set; }
    }
}
