//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarbiTtiTFA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolMiembro
    {
        public int IDRolMiembro { get; set; }
        public Nullable<int> IDMiembro { get; set; }
        public Nullable<int> IDRol { get; set; }
    }
}
